<?php

return [
    'functions' => [
        'admin.documentation.view' => ['description' => 'View admin documentation dashboard', 'status' => 'active'],
        'admin.documentation.tasks.manage' => ['description' => 'Create, update, toggle, and delete documentation tasks', 'status' => 'active'],
        'admin.menus.manage' => ['description' => 'Create, update, remove, and order frontend/admin menu items', 'status' => 'active'],
        'admin.permissions.manage' => ['description' => 'Create and sync platform permissions', 'status' => 'active'],
        'admin.vvvebjs.manage' => ['description' => 'Manage VvvebJs pages, ordered headers, footers, and blocks', 'status' => 'active'],
        'admin.plugins.view' => ['description' => 'View installed plugins', 'status' => 'active'],
        'admin.plugins.install' => ['description' => 'Install already discovered plugins', 'status' => 'active'],
        'admin.plugins.activate' => ['description' => 'Activate and deactivate plugins', 'status' => 'active'],
        'admin.roles.manage' => ['description' => 'Create and update platform roles', 'status' => 'active'],
        'admin.settings.manage' => ['description' => 'Update platform settings', 'status' => 'active'],
        'admin.users.manage' => ['description' => 'Create and update platform users', 'status' => 'active'],
        'platform.registry.view' => ['description' => 'View platform functions, hooks, routes, and success/error logs', 'status' => 'active'],
        'platform.registry.backups.manage' => ['description' => 'Create manual platform backup checkpoints and view backup/report governance tabs', 'status' => 'active'],
        'auth.login' => ['description' => 'Authenticate users', 'status' => 'active'],
        'auth.password_reset' => ['description' => 'Request and reset passwords', 'status' => 'active'],
        'profile.manage' => ['description' => 'Manage authenticated user profile', 'status' => 'active'],
        'ai.intent.route' => ['description' => 'Route AI messages by intent, permission, usage, and data-access policy', 'status' => 'active'],
        'ai.data.tools.execute' => ['description' => 'Execute permission-aware read-only AI data tools', 'status' => 'active'],
    ],

    'hooks' => [
        'plugin.installing' => ['type' => 'action', 'description' => 'Before plugin installation', 'status' => 'active'],
        'plugin.installed' => ['type' => 'action', 'description' => 'After plugin installation', 'status' => 'active'],
        'plugin.activating' => ['type' => 'action', 'description' => 'Before plugin activation', 'status' => 'active'],
        'plugin.activated' => ['type' => 'action', 'description' => 'After plugin activation', 'status' => 'active'],
        'plugin.deactivating' => ['type' => 'action', 'description' => 'Before plugin deactivation', 'status' => 'active'],
        'plugin.deactivated' => ['type' => 'action', 'description' => 'After plugin deactivation', 'status' => 'active'],
        'plugin.uninstalling' => ['type' => 'action', 'description' => 'Before plugin uninstall', 'status' => 'active'],
        'plugin.uninstalled' => ['type' => 'action', 'description' => 'After plugin uninstall', 'status' => 'active'],
        'plugin.routes.loading' => ['type' => 'action', 'description' => 'Before plugin route file loading', 'status' => 'active'],
        'plugin.routes.loaded' => ['type' => 'action', 'description' => 'After plugin route file loading', 'status' => 'active'],
        'plugin.permissions.registering' => ['type' => 'action', 'description' => 'Before plugin permissions are registered', 'status' => 'active'],
        'plugin.permissions.registered' => ['type' => 'action', 'description' => 'After plugin permissions are registered', 'status' => 'active'],
        'plugin.menus.registering' => ['type' => 'action', 'description' => 'Before plugin menus are registered', 'status' => 'active'],
        'plugin.menus.registered' => ['type' => 'action', 'description' => 'After plugin menus are registered', 'status' => 'active'],
        'frontend.menu.items' => ['type' => 'filter', 'description' => 'Filter the ordered parent/submenu tree for a frontend menu key before rendering', 'status' => 'active'],
        'frontend.menu.html' => ['type' => 'filter', 'description' => 'Filter the final frontend menu HTML rendered by a VvvebJs menu hook', 'status' => 'active'],
        'theme.resolving' => ['type' => 'filter', 'description' => 'Before active theme resolution', 'status' => 'active'],
        'theme.resolved' => ['type' => 'filter', 'description' => 'After active theme resolution', 'status' => 'active'],
        'asset.publishing' => ['type' => 'action', 'description' => 'Before asset publishing', 'status' => 'active'],
        'asset.published' => ['type' => 'action', 'description' => 'After asset publishing', 'status' => 'active'],
    ],

    'routes' => [
        'front.home' => ['uri' => '/', 'methods' => ['GET', 'HEAD'], 'description' => 'Frontend home', 'status' => 'active'],
        'front.account' => ['uri' => 'account', 'methods' => ['GET', 'HEAD'], 'description' => 'Authenticated user account', 'status' => 'active'],
        'ai.message' => ['uri' => 'ai/message', 'methods' => ['POST'], 'description' => 'Laravel AI intent routing endpoint', 'status' => 'active'],
        'dashboard' => ['uri' => 'dashboard', 'methods' => ['GET', 'HEAD'], 'description' => 'Staff dashboard', 'status' => 'active'],
        'profile.edit' => ['uri' => 'profile', 'methods' => ['GET', 'HEAD'], 'description' => 'Edit profile', 'status' => 'active'],
        'profile.update' => ['uri' => 'profile', 'methods' => ['PATCH'], 'description' => 'Update profile', 'status' => 'active'],
        'profile.destroy' => ['uri' => 'profile', 'methods' => ['DELETE'], 'description' => 'Delete profile', 'status' => 'active'],
        'login' => ['uri' => 'login', 'methods' => ['GET', 'HEAD'], 'description' => 'Login form', 'status' => 'active'],
        'logout' => ['uri' => 'logout', 'methods' => ['POST'], 'description' => 'Logout', 'status' => 'active'],
        'auth.login.store' => ['uri' => 'login', 'methods' => ['POST'], 'description' => 'Submit login credentials', 'status' => 'active'],
        'auth.register.store' => ['uri' => 'register', 'methods' => ['POST'], 'description' => 'Create frontend user account', 'status' => 'active'],
        'password.confirm.store' => ['uri' => 'confirm-password', 'methods' => ['POST'], 'description' => 'Confirm current password', 'status' => 'active'],
        'register' => ['uri' => 'register', 'methods' => ['GET', 'HEAD'], 'description' => 'Registration form', 'status' => 'active'],
        'password.request' => ['uri' => 'forgot-password', 'methods' => ['GET', 'HEAD'], 'description' => 'Forgot password form', 'status' => 'active'],
        'password.email' => ['uri' => 'forgot-password', 'methods' => ['POST'], 'description' => 'Send password reset link', 'status' => 'active'],
        'password.reset' => ['uri' => 'reset-password/{token}', 'methods' => ['GET', 'HEAD'], 'description' => 'Password reset form', 'status' => 'active'],
        'password.store' => ['uri' => 'reset-password', 'methods' => ['POST'], 'description' => 'Store reset password', 'status' => 'active'],
        'password.confirm' => ['uri' => 'confirm-password', 'methods' => ['GET', 'HEAD'], 'description' => 'Confirm password form', 'status' => 'active'],
        'password.update' => ['uri' => 'password', 'methods' => ['PUT'], 'description' => 'Update password', 'status' => 'active'],
        'verification.notice' => ['uri' => 'verify-email', 'methods' => ['GET', 'HEAD'], 'description' => 'Email verification notice', 'status' => 'active'],
        'verification.send' => ['uri' => 'email/verification-notification', 'methods' => ['POST'], 'description' => 'Send email verification', 'status' => 'active'],
        'verification.verify' => ['uri' => 'verify-email/{id}/{hash}', 'methods' => ['GET', 'HEAD'], 'description' => 'Verify email', 'status' => 'active'],
        'admin.documentation.*' => ['uri' => 'admin/documentation*', 'methods' => ['GET', 'POST', 'PATCH', 'DELETE'], 'description' => 'Documentation admin routes', 'status' => 'active'],
        'admin.menus.*' => ['uri' => 'admin/menus*', 'methods' => ['GET', 'POST', 'PATCH', 'DELETE'], 'description' => 'Frontend and admin menu settings routes', 'status' => 'active'],
        'admin.plugins.*' => ['uri' => 'admin/plugins*', 'methods' => ['GET', 'POST', 'PATCH'], 'description' => 'Plugin admin routes', 'status' => 'active'],
        'admin.users.*' => ['uri' => 'admin/users*', 'methods' => ['GET', 'POST', 'PATCH'], 'description' => 'User admin routes', 'status' => 'active'],
        'admin.roles.*' => ['uri' => 'admin/roles*', 'methods' => ['GET', 'POST', 'PATCH'], 'description' => 'Role admin routes', 'status' => 'active'],
        'admin.permissions.*' => ['uri' => 'admin/permissions*', 'methods' => ['GET', 'POST'], 'description' => 'Permission admin routes', 'status' => 'active'],
        'admin.settings.*' => ['uri' => 'admin/settings*', 'methods' => ['GET', 'PATCH'], 'description' => 'Settings admin routes', 'status' => 'active'],
        'admin.backups.*' => ['uri' => 'admin/backups*', 'methods' => ['GET', 'POST', 'DELETE'], 'description' => 'Super-admin system backup checkpoint routes', 'status' => 'active'],
        'admin.media.*' => ['uri' => 'admin/media*', 'methods' => ['GET', 'POST', 'PATCH', 'DELETE'], 'description' => 'Media library upload, SEO metadata, and bulk delete routes', 'status' => 'active'],
        'admin.pages.*' => ['uri' => 'admin/pages*', 'methods' => ['GET', 'POST', 'PATCH', 'DELETE'], 'description' => 'Content page management routes', 'status' => 'active'],
        'admin.vvveb.*' => ['uri' => 'admin/vvveb-layout*', 'methods' => ['GET', 'HEAD', 'PUT'], 'description' => 'Ordered Theme Layout composition', 'status' => 'active'],
        'admin.platform-registry.*' => ['uri' => 'admin/platform-registry*', 'methods' => ['GET', 'POST', 'DELETE'], 'description' => 'Super-admin platform registry, backup, restore, remove, and report pages', 'status' => 'active'],
        'storage.local' => ['uri' => 'storage/{path}', 'methods' => ['GET', 'HEAD'], 'description' => 'Local storage file route', 'status' => 'active'],
        'storage.local.upload' => ['uri' => 'storage/{path}', 'methods' => ['PUT'], 'description' => 'Local storage upload route', 'status' => 'active'],
        'generated::*' => ['uri' => 'framework/generated', 'methods' => ['GET', 'HEAD', 'POST'], 'description' => 'Framework generated unnamed route names', 'status' => 'active'],
    ],

    'plugin_route_files' => [
        '*' => [
            'web' => true,
            'admin' => true,
            'api' => true,
        ],
    ],
];
